### PR TITLE
Vacant 1.1.2

### PR DESCRIPTION
**Pull request by Laugic**

### CODE REVIEW

**Comment by OceanUwU** [comment]
this pr doesn't edit the main data files

**Comment by Laugic** [comment]
It doesn't? I see Vacant's data file having changes in it, but is it missing something? Do you mean the character.js? Vacant should already be in there from before.

**Comment by OceanUwU** [comment]
export/dataFormatted.js

**Comment by Laugic** [comment]
Ok hopefully that fixed it

**Pull request merged**
